using Godot;
using Waterways;

public partial class RiverBridge : Node3D
{
    public override void _Ready()
    {
        CallDeferred(nameof(SetupCollision));
    }

    private void SetupCollision()
    {
        var manager = GetNodeOrNull<RiverManager>("RiverManager");
        if (manager == null) return;

        // Wait a bit for the mesh to be generated by Waterways
        var meshInstance = manager.GetNodeOrNull<MeshInstance3D>("BaseGeneratorMeshInstance");
        if (meshInstance != null && meshInstance.Mesh != null)
        {
            meshInstance.CreateTrimeshCollision();
            var staticBody = meshInstance.GetNodeOrNull<StaticBody3D>(meshInstance.Name + "_col");
            if (staticBody != null)
            {
                staticBody.CollisionLayer = 2; // Water Layer
                staticBody.CollisionMask = 0;
            }
        }
    }
}
